### ISSUE TITLE
Material labels for released dataset?

### ISSUE THREAD

**Issue by Jerrypiglet** [jingsenzhu/i2-sdf#4]
Hi there, thanks for releasing the two demo scenes! I wonder if there is a plan to include materials and emitter mask in the current/later version (as indicated [here](https://github.com/jingsenzhu/i2-sdf/blob/main/DATA_CONVENTION.md)), which will be useful for inverse rendering tasks.

Thanks!

**Comment by jingsenzhu** [comment]
We disable materials and emitter masks in scenes which contain complex material (e.g. dielectric material with refractions), which our adopted GGX BRDF model in the inverse rendering framework does not support. For scenes where all materials are GGX, we will release their materials and emitter masks.

**Comment by Jerrypiglet** [comment]
Thanks for the explanation! I understand that scenes with complex BRDF should not be evaluated against GT $f_d$ and $f_s$. However it is still possible to acquire $f_s$ and $f_d$ from GT BRDF and use them as reference (pseudo ground truth), so I think it might be helpful to have access to labels of complex BRDF for qualitative comparison despite its difference with the assumed GGX BRDF.

Also I wonder if there is a plan to release the GT mesh (and maybe the scene file)? I understand there might be concerns on IP of assets, however I wonder if it is possible to release some form of degraded mesh geometry in 3D(e.g. convert the original set of objects into one mesh, and possibly re-meshed, downsampled, or converted to TSDF), as well as emitters and BRDF in 3D? Right now the released data consist of modalities in 2D, which may not allow re-rendering or evaluation of geometry/material/lighting in full 3D or in novel views.

**Comment by jingsenzhu** [comment]
1. I don't think dielectric BRDF can be pseudo-labeled by GGX BRDF parameters, because our adopted GGX BRDF has no ability to handle refractions. Nevertheless, dielectric BRDFs usually takes up a small part of the scene, so I can provide a mask of these areas, while the BRDF parameters in other (most part of) areas using GGX BRDF can be normally provided.
2. About GT mesh, this indeed involves commercial copyright issues (the scenes are designed for commercial use, and rendered by commercial rendering engines), so the original GT mesh and scene files cannot be released. As for your proposal for providing degraded scenes, I will communicate with the copyright owner and inform you later.

**Comment by Jerrypiglet** [comment]
> 1. I don't think dielectric BRDF can be pseudo-labeled by GGX BRDF parameters, because our adopted GGX BRDF has no ability to handle refractions. Nevertheless, dielectric BRDFs usually takes up a small part of the scene, so I can provide a mask of these areas, while the BRDF parameters in other (most part of) areas using GGX BRDF can be normally provided.
> 2. About GT mesh, this indeed involves commercial copyright issues (the scenes are designed for commercial use, and rendered by commercial rendering engines), so the original GT mesh and scene files cannot be released. As for your proposal for providing degraded scenes, I will communicate with the copyright owner and inform you later.

Thanks for checking! Replica authors had similar issues with releasing original scene files, so they managed to back-project and fuse textures onto the mesh as HDR texture and got a license to release those, although it's less helpful for evaluating view-dependent effects. It will be great if something similar can be done with your dataset.

**Comment by jingsenzhu** [comment]
After communicating with the copyright owner, we decide to release a pointcloud sampled by poisson sampling from the GT mesh to enable 3D reconstruction evaluations. However, I'm sorry that I'm not granted to release texture information :(

**Comment by Jerrypiglet** [comment]
> After communicating with the copyright owner, we decide to release a pointcloud sampled by poisson sampling from the GT mesh to enable 3D reconstruction evaluations. However, I'm sorry that I'm not granted to release texture information :(

Great! Thanks!
